# Generated by Django 5.0.6 on 2024-07-14 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userLogin', '0006_student_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('fullMark', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userLogin.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examType', models.CharField(max_length=100)),
                ('examName', models.CharField(max_length=100)),
                ('examScore', models.TextField(max_length=8000)),
                ('selfEvaluation', models.TextField(max_length=8000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userLogin.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examData', models.TextField(max_length=8000)),
                ('examSummary', models.TextField(max_length=8000)),
                ('uesr', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
