# Generated by Django 5.0.6 on 2024-07-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examsummary',
            old_name='uesr',
            new_name='user',
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='education_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examinfo',
            name='totalScore',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='fullMark',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='examScore',
            field=models.JSONField(null=True),
        ),
    ]
