# Generated by Django 5.0.6 on 2024-07-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkApi', '0002_rename_uesr_examsummary_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('mood', models.CharField(default='平常心', max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
