# Generated by Django 5.0.6 on 2024-08-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkApi', '0006_document_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
