# Generated by Django 5.0.6 on 2024-07-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_num',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
