# Generated by Django 5.0.6 on 2024-07-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0002_alter_user_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
